version: '3'

services:
  # PHP (with Nginx)
  app:
    image: ambientum/php:7.3-nginx
    container_name: blog-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
      - "8083:8083"
